###############################################################################
#                                                                             #
# neutron.mac                                                                 #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################
#
#
# verbosities
#/control/verbose 1
#/run/verbose 1 //usually 1
#/tracking/verbose 1
#/hits/verbose 2

#
# draw flags
/dmx/draw/drawColours custom
/dmx/draw/gammaColour green
/dmx/draw/drawTracks noscint
/dmx/draw/drawHits 1
#
# file output
/dmx/savePmt  0
/dmx/saveHits 1
#
# kill gammas in lab wall
/dmx/KillGammasInConcrete 0
#
# radioactive decay module
/process/had/rdm/verbose 0
/process/had/rdm/allVolumes
#
# gun: particle
/dmx/gun/verbose 0
/dmx/gun/particle neutron
/dmx/gun/energytype Mono
/dmx/gun/energy 3 MeV
#
# gun: isotropic
# /dmx/gun/angtype iso
#
# OR gun: shoot at detector
/dmx/gun/angtype direction
/dmx/gun/direction 0 0 1
#
# gun: source
/dmx/gun/type Volume
/dmx/gun/shape Cylinder
/dmx/gun/radius 2.50 mm
/dmx/gun/halfz 10.0 mm
/dmx/gun/centre 0 0 -30 cm
#
/dmx/hitsfile 10000neutron3MeVwHuber.out
/dmx/pmtfile neutron_pmt.out
/dmx/histogramfile 10000neutron3MeVwHuber
#
/run/beamOn 10000
