/run/initialize 

/vis/heprep/setFileName RandomizeVisSmaller4
/vis/open HepRepFile
/vis/scene/create
/vis/scene/endOfEventAction accumulate
/vis/scene/add/volume
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/scene/add/hits
# /vis/scene/add/logicalVolume

# /vis/heprep/appendGeometry false 
# /vis/heprep/addPointAttributes 0 

#/seed/setSeeds 123456   #Not actually random - baseline to get reproducability
# /control/verbose 1
 /run/verbose 2
 /event/verbose 2
 /tracking/verbose 2

/dmx/gun/particle neutron
/dmx/gun/energy 3 MeV
#/dmx/gun/position 0 0 -30 cm
#/dmx/gun/direction 0 0 1
/dmx/gun/shape Shell
/dmx/gun/angtype randominward

/run/beamOn 1