/run/initialize 

/vis/heprep/setFileName Neutron1MeVGeomTestv28
/vis/open HepRepFile
/vis/scene/create
/vis/scene/add/volume
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/scene/add/hits
# /vis/scene/add/logicalVolume

# /vis/heprep/appendGeometry false  
# /vis/heprep/addPointAttributes 0 

#/seed/setSeeds 123456   #Not actually random - baseline to get reproducability
# /control/verbose 1
# /run/verbose 1
# /event/verbose 1
# /tracking/verbose 1

/dmx/gun/particle neutron
/dmx/gun/energy 3 MeV
/dmx/gun/position 0 0 28 cm
/dmx/gun/direction 0 0 -1

/run/beamOn 1